{{- if eq .Values.tracing.mode "test" -}}
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
    jaegertracing.io/operated-by: openshift-distributed-tracing.jaeger-operator
  name: jaeger-all-in-one-inmemory
  namespace: {{ .Values.tracing.namespace }}
spec:
  agent:
    config: {}
    options: {}
    resources: {}
  allInOne:
    config: {}
    metricsStorage: {}
    options:
      log-level: info
    resources: {}
  collector:
    config: {}
    kafkaSecretName: ""
    options: {}
    resources: {}
  ingester:
    config: {}
    kafkaSecretName: ""
    options: {}
    resources: {}
  ingress:
    openshift:
      sar: '{"namespace": "{{ .Values.tracing.namespace }}", "resource": "pods", "verb": "get"}'
    options: {}
    resources: {}
    security: oauth-proxy
  query:
    metricsStorage: {}
    options: {}
    resources: {}
  resources: {}
  sampling:
    options: {}
  storage:
    cassandraCreateSchema: {}
    dependencies:
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      name: elasticsearch
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: "1"
          memory: 16Gi
      storage: {}
    esIndexCleaner:
      numberOfDays: 7
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      resources: {}
      schedule: 0 0 * * *
    grpcPlugin: {}
    options: {}
    type: memory
  strategy: allinone
  ui:
    options:
      menu:
      - items:
        - label: Documentation
          url: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/distributed_tracing/index
        label: About
      - anchorTarget: _self
        label: Log Out
        url: /oauth/sign_in
{{- end }}
