apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simpleapp.fullname" . }}-simplewebapp-v2
  #annotations:
  #  sidecar.jaegertracing.io/inject: "true"
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "simpleapp.selectorLabels" . | nindent 6 }}
      app: simplewebapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "simpleapp.selectorLabels" . | nindent 8 }}
        app: simplewebapp
        sidecar.istio.io/inject: "true"
        version: v2
    spec:
      containers:
      - image: {{ .Values.webapp.image }}
        imagePullPolicy: Always
        name: webapp
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: HELLOMSG
            value: "Hello you!"
          - name: TRACE_COLLECTOR
            value: "{{ .Values.traceCollector }}"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"     
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault        
      terminationGracePeriodSeconds: 30
      serviceAccountName: simplewebapp
