apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simpleapi
    app.kubernetes.io/component: simpleapi
    app.kubernetes.io/instance: simpleapi
    app.kubernetes.io/name: simpleapi
    app.kubernetes.io/part-of: simpleapi
  name: {{ include "simpleapp.fullname" . }}-simpleapi
  #annotations:
  #  sidecar.jaegertracing.io/inject: "true"
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "simpleapp.selectorLabels" . | nindent 6 }}
      app: simpleapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "simpleapp.selectorLabels" . | nindent 8 }}
        app: simpleapi
        deploymentconfig: simpleapi
        version: v1
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: {{ .Values.api.image }}
        imagePullPolicy: Always
        name: simpleapi
        env:
          - name: TRACE_COLLECTOR
            value: "{{ .Values.traceCollector }}"
        ports:
        - containerPort: 2112
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: simpleapi
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault        
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simpleapi
    app.kubernetes.io/component: simpleapi
    app.kubernetes.io/instance: simpleapi
    app.kubernetes.io/name: simpleapi
    app.kubernetes.io/part-of: simpleapi
    app.openshift.io/runtime-version: v0.0.1
  name: simpleapi
spec:
  ports:
  - name: tcp-2112
    port: 2112
    protocol: TCP
    targetPort: 2112
  - name: tcp-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simpleapi
    deploymentconfig: simpleapi
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: simpleapi
#apiVersion: route.openshift.io/v1
#kind: Route
#metadata:
#  labels:
#    app: example-app
#    app.kubernetes.io/component: example-app
#    app.kubernetes.io/instance: example-app
#    app.kubernetes.io/name: example-app
#    app.kubernetes.io/part-of: example-app
#    app.openshift.io/runtime-version: v0.0.2
#  name: example-app
#spec:
#  port:
#    targetPort: 8080-tcp
#  tls:
#    insecureEdgeTerminationPolicy: Redirect
#    termination: edge
#  to:
#    kind: Service
#    name: example-app
#    weight: 100
#  wildcardPolicy: None
#
